### Numpy

NumPy is a Python library for numerical computing. It provides a powerful object called the ndarray (n-dimensional array) that allows you to store and perform mathematical operations on large datasets efficiently. NumPy is widely used in data science, machine learning, and scientific applications because it makes array and matrix operations fast and easy.

In [1]:
!pip install numpy 

In [ ]:
import numpy as np

## Create array using numpy
## Create a 1D array 

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) ## checking the shape 
                  ## output : (5,),it means 1D  ## The first number (5) = how many elements are in the array → here there are 5 numbers.

                                                ## The comma ( , ) = tells us this is 1-dimensional (just a single row/line of numbers)./( “This is a 1D array with 5 elements.”)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1D array 

arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## it means 1 row and 5 colomns 

array([[1, 2, 3, 4, 5]])

In [11]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array 

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)  ## 2 rows and 5 colomns 

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0,10,2)  ##Meaning (in simple words):
#-> 0 → start from 0
#-> 10 → go up to 10 (but not including 10)
#-> 2 → step size (jump by 2 each time)



array([0, 2, 4, 6, 8])

In [19]:
np.arange(0,10,2).reshape(5,1) ## 5 rows and 1 colomns 

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## identy matrix 

np.eye(3)  ## 3 by 3 matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of numpy

arr =np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr) 
print("Shape:",arr.shape)  ## output:  (2,3)
print("Number of domentions:",arr.ndim)  ## output: 2
print("Size (number of leements):",arr.size) ## ouyput: 6
print("Data type:",arr.dtype)  ## output : int64 (may vary based on platform)
print("Item size(in btypes):",arr.itemsize) ## output: 8 

## bytes → built-in Python datatype for binary data.
## btypes → not built-in; likely part of some external module.

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of domention: 2
Size (number of leements): 6
Data type: int64
Item size(in btypes): 8


In [30]:
## Numpy  Vectorized Operation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise addition 
print("Addition:",arr1+arr2)

## Element wise Subdtraction
print("Substration:",arr1-arr2)

## Element wise Multiplicatio
print("Multiplication:",arr1*arr2)

## Element wise Division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substration: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [32]:
## Univarsal Function

arr=np.array([2,3,4,5,6])

## Square root 
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log 
print(np.log(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [33]:
## Array Slicing and Indexing 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Arrya: \n",arr)

Arrya: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
arr[0][0]


np.int64(1)

In [46]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])